### ISSUE TITLE
Error: You need to provide explicit type for Edge#cursor !

### ISSUE THREAD

**Issue by kodeine** [kazekyo/nestjs-graphql-relay#3]
getting the above error, any ideas?

**Comment by kazekyo** [comment]
I have updated libraries such as NestJs 🎉 
In this [PR](https://github.com/kazekyo/nestjs-graphql-relay/pull/4), I confirmed that I could generate seed data and run a sample query(see [README](https://github.com/kazekyo/nestjs-graphql-relay/blob/master/README.md)).
Please check [new code](https://github.com/kazekyo/nestjs-graphql-relay/blob/master/src/common/connection-paging.ts) and run  the sample query.

If you still get the error, please share details.
